# Generated by Django 3.2.6 on 2021-09-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
