# Generated by Django 3.2.6 on 2021-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0004_auto_20210913_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=3, null=True),
        ),
    ]
