# Generated by Django 3.2.6 on 2021-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0005_extendeduser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='', max_length=20, null=True),
        ),
    ]
