# Generated by Django 3.2.6 on 2021-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0006_auto_20210914_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20, null=True),
        ),
    ]
