# Generated by Django 3.2.6 on 2021-10-31 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_rename_phone_number_extendeduser_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='firstname',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='lstname',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE'), ('Others', 'Others')], default='', max_length=20, null=True),
        ),
    ]
