# Generated by Django 3.2.6 on 2021-11-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20211031_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='lstname',
        ),
    ]
